[build]
  command = "docusaurus build"
  publish = "build/"

[build.environment]
  NODE_VERSION="14.15.4"

[context.production.environment]
  SITE_URL="https://www.webpackersurvival.guide"

[context.deploy-preview.environment]
  SITE_URL="https://example.com"
